global:
  resolve_timeout: 5m

route:
  group_by: ['job', 'severity']
  receiver: 'default-receiver'

receivers:
- name: 'default-receiver'
  webhook_configs:
  - url: 'https://strix-tools.mni.thm.de/api/v1/external/alertmanager?api_key=FtwVrgC4gPtfj3zXzAifyVLvY8XofuhD&stream=4'
    http_config:
      tls_config:
        insecure_skip_verify: true
